// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TesouroDireto.Infrastructure.Persistence;

#nullable disable

namespace TesouroDireto.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TesouroDireto.Domain.PrecosTaxas.PrecoTaxa", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DataBase")
                        .HasColumnType("date")
                        .HasColumnName("data_base");

                    b.Property<decimal>("PuBase")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("pu_base");

                    b.Property<decimal>("PuCompra")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("pu_compra");

                    b.Property<decimal>("PuVenda")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("pu_venda");

                    b.Property<decimal>("TaxaCompra")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("taxa_compra");

                    b.Property<decimal>("TaxaVenda")
                        .HasPrecision(10, 4)
                        .HasColumnType("numeric(10,4)")
                        .HasColumnName("taxa_venda");

                    b.Property<Guid>("TituloId")
                        .HasColumnType("uuid")
                        .HasColumnName("titulo_id");

                    b.HasKey("Id");

                    b.HasIndex("TituloId", "DataBase")
                        .IsUnique()
                        .HasDatabaseName("ix_precos_taxas_titulo_data");

                    b.ToTable("precos_taxas", (string)null);
                });

            modelBuilder.Entity("TesouroDireto.Domain.Titulos.Titulo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("date")
                        .HasColumnName("data_vencimento");

                    b.Property<string>("Indexador")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("indexador");

                    b.Property<bool>("PagaJurosSemestrais")
                        .HasColumnType("boolean")
                        .HasColumnName("paga_juros_semestrais");

                    b.Property<string>("TipoTitulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("tipo_titulo");

                    b.HasKey("Id");

                    b.HasIndex("TipoTitulo", "DataVencimento")
                        .IsUnique()
                        .HasDatabaseName("ix_titulos_tipo_vencimento");

                    b.ToTable("titulos", (string)null);
                });

            modelBuilder.Entity("TesouroDireto.Domain.Tributos.Tributo", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("BaseCalculo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("base_calculo");

                    b.Property<bool>("Cumulativo")
                        .HasColumnType("boolean")
                        .HasColumnName("cumulativo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<string>("TipoCalculo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_calculo");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_tributos_nome");

                    b.ToTable("tributos", (string)null);
                });

            modelBuilder.Entity("TesouroDireto.Domain.PrecosTaxas.PrecoTaxa", b =>
                {
                    b.HasOne("TesouroDireto.Domain.Titulos.Titulo", null)
                        .WithMany()
                        .HasForeignKey("TituloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TesouroDireto.Domain.Tributos.Tributo", b =>
                {
                    b.OwnsMany("TesouroDireto.Domain.Tributos.Faixa", "Faixas", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasColumnName("id");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<decimal>("Aliquota")
                                .HasPrecision(8, 4)
                                .HasColumnType("numeric(8,4)")
                                .HasColumnName("aliquota");

                            b1.Property<int?>("Dia")
                                .HasColumnType("integer")
                                .HasColumnName("dia");

                            b1.Property<int?>("DiasMax")
                                .HasColumnType("integer")
                                .HasColumnName("dias_max");

                            b1.Property<int?>("DiasMin")
                                .HasColumnType("integer")
                                .HasColumnName("dias_min");

                            b1.Property<Guid>("TributoId")
                                .HasColumnType("uuid")
                                .HasColumnName("tributo_id");

                            b1.HasKey("Id");

                            b1.HasIndex("TributoId");

                            b1.ToTable("tributo_faixas", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TributoId");
                        });

                    b.Navigation("Faixas");
                });
#pragma warning restore 612, 618
        }
    }
}
