apiVersion: 1
contactPoints:
  - orgId: 1
    name: telegram-tesouro
    receivers:
      - uid: td-telegram-receiver
        type: telegram
        settings:
          bottoken: '${TELEGRAM_BOT_TOKEN}'
          chatid: "144442958"
        disableResolveMessage: false
