apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://tesouro-direto-prometheus:9090/prometheus
    isDefault: true
    editable: false

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://tesouro-direto-loki:3100
    editable: false
    jsonData:
      derivedFields:
        - name: CorrelationId
          matcherRegex: '"CorrelationId":"([^"]+)"'
          url: ''
          datasourceUid: self
